---
roles:
  - name: geerlingguy.pip
    version: 3.1.0
    src: https://github.com/geerlingguy/ansible-role-pip.git
  - name: geerlingguy.docker
    version: 7.5.1
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.3.0
