---
roles:
  - name: geerlingguy.pip
    version: 3.1.0
    src: https://github.com/geerlingguy/ansible-role-pip.git
  - name: geerlingguy.docker
    version: 7.4.5
collections:
  - name: ansible.posix
    version: 2.0.0
    src: https://github.com/ansible-collections/ansible.posix.git
  - name: manala.roles
    version: 4.4.0
