---
roles:
  - name: manala.bind
    version: 2.0.2
    src: https://github.com/manala/ansible-role-bind.git
collections:
  - name: ansible.posix
    version: 1.1.1
    src: https://github.com/ansible-collections/ansible.posix.git
...
