---
roles:
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.docker
    version: 7.8.0
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.4.1
